  defmodule Anoncreds do
        def issuer_create_schema(issuer_did,name,version,attrs), do: Indy.issuer_create_schema(issuer_did,name,version,attrs)
  def issuer_create_and_store_credential_def(wallet_handle,issuer_did,schema_json,tag,signature_type,config_json), do: Indy.issuer_create_and_store_credential_def(wallet_handle,issuer_did,schema_json,tag,signature_type,config_json)
  def issuer_create_and_store_revoc_reg(wallet_handle,issuer_did,revoc_def_type,tag,cred_def_id,config_json,tails_writer_handle), do: Indy.issuer_create_and_store_revoc_reg(wallet_handle,issuer_did,revoc_def_type,tag,cred_def_id,config_json,tails_writer_handle)
  def issuer_create_credential_offer(wallet_handle,cred_def_id), do: Indy.issuer_create_credential_offer(wallet_handle,cred_def_id)
  def issuer_create_credential(wallet_handle,cred_offer_json,cred_req_json,cred_values_json,rev_reg_id,blob_storage_reader_handle), do: Indy.issuer_create_credential(wallet_handle,cred_offer_json,cred_req_json,cred_values_json,rev_reg_id,blob_storage_reader_handle)
  def issuer_revoke_credential(wallet_handle,blob_storage_reader_cfg_handle,rev_reg_id,cred_revoc_id), do: Indy.issuer_revoke_credential(wallet_handle,blob_storage_reader_cfg_handle,rev_reg_id,cred_revoc_id)
  def issuer_merge_revocation_registry_deltas(rev_reg_delta_json,other_rev_reg_delta_json), do: Indy.issuer_merge_revocation_registry_deltas(rev_reg_delta_json,other_rev_reg_delta_json)
  def prover_create_master_secret(wallet_handle,master_secret_id), do: Indy.prover_create_master_secret(wallet_handle,master_secret_id)
  def prover_create_credential_req(wallet_handle,prover_did,cred_offer_json,cred_def_json,master_secret_id), do: Indy.prover_create_credential_req(wallet_handle,prover_did,cred_offer_json,cred_def_json,master_secret_id)
  def prover_store_credential(wallet_handle,cred_id,cred_req_metadata_json,cred_json,cred_def_json,rev_reg_def_json), do: Indy.prover_store_credential(wallet_handle,cred_id,cred_req_metadata_json,cred_json,cred_def_json,rev_reg_def_json)
  def prover_get_credential(wallet_handle,cred_id), do: Indy.prover_get_credential(wallet_handle,cred_id)
  def prover_search_credentials(wallet_handle,query_json), do: Indy.prover_search_credentials(wallet_handle,query_json)
  def prover_fetch_credentials(search_handle,count), do: Indy.prover_fetch_credentials(search_handle,count)
  def prover_close_credentials_search(search_handle), do: Indy.prover_close_credentials_search(search_handle)
  def prover_search_credentials_for_proof_req(wallet_handle,proof_request_json,extra_query_json), do: Indy.prover_search_credentials_for_proof_req(wallet_handle,proof_request_json,extra_query_json)
  def prover_fetch_credentials_for_proof_req(search_handle,item_referent,count), do: Indy.prover_fetch_credentials_for_proof_req(search_handle,item_referent,count)
  def prover_close_credentials_search_for_proof_req(search_handle), do: Indy.prover_close_credentials_search_for_proof_req(search_handle)
  def prover_create_proof(wallet_handle,proof_req_json,requested_credentials_json,master_secret_id,schemas_json,credential_defs_json,rev_states_json), do: Indy.prover_create_proof(wallet_handle,proof_req_json,requested_credentials_json,master_secret_id,schemas_json,credential_defs_json,rev_states_json)
  def verifier_verify_proof(proof_request_json,proof_json,schemas_json,credential_defs_json,rev_reg_defs_json,rev_regs_json), do: Indy.verifier_verify_proof(proof_request_json,proof_json,schemas_json,credential_defs_json,rev_reg_defs_json,rev_regs_json)
  def create_revocation_state(blob_storage_reader_handle,rev_reg_def_json,rev_reg_delta_json,timestamp,cred_rev_id), do: Indy.create_revocation_state(blob_storage_reader_handle,rev_reg_def_json,rev_reg_delta_json,timestamp,cred_rev_id)
  def update_revocation_state(blob_storage_reader_handle,rev_state_json,rev_reg_def_json,rev_reg_delta_json,timestamp,cred_rev_id), do: Indy.update_revocation_state(blob_storage_reader_handle,rev_state_json,rev_reg_def_json,rev_reg_delta_json,timestamp,cred_rev_id)

  end
